package com.example.miaosha.dataobject;

public class UserPasswordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.id
     *
     * @mbg.generated Sun Apr 12 00:06:35 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.encrpt_passsword
     *
     * @mbg.generated Sun Apr 12 00:06:35 CST 2020
     */
    private String encrptPasssword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.user_id
     *
     * @mbg.generated Sun Apr 12 00:06:35 CST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.id
     *
     * @return the value of user_password.id
     *
     * @mbg.generated Sun Apr 12 00:06:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.id
     *
     * @param id the value for user_password.id
     *
     * @mbg.generated Sun Apr 12 00:06:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.encrpt_passsword
     *
     * @return the value of user_password.encrpt_passsword
     *
     * @mbg.generated Sun Apr 12 00:06:35 CST 2020
     */
    public String getEncrptPasssword() {
        return encrptPasssword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.encrpt_passsword
     *
     * @param encrptPasssword the value for user_password.encrpt_passsword
     *
     * @mbg.generated Sun Apr 12 00:06:35 CST 2020
     */
    public void setEncrptPasssword(String encrptPasssword) {
        this.encrptPasssword = encrptPasssword == null ? null : encrptPasssword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.user_id
     *
     * @return the value of user_password.user_id
     *
     * @mbg.generated Sun Apr 12 00:06:35 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.user_id
     *
     * @param userId the value for user_password.user_id
     *
     * @mbg.generated Sun Apr 12 00:06:35 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}